<a href="https://colab.research.google.com/github/GauraoM/Machine-Learning-Tutorial-Python/blob/main/K_Fold_Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_iris

In [2]:
# Load the datset
iris = load_iris()

In [3]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [5]:
# Splitting the data into train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(iris.data, iris.target, test_size=0.3) 

##### Linear Regression

In [8]:
# Creating an object,training and testing the model
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test, y_test)

0.9111111111111111

##### SVM

In [9]:
# Creating an object,training and testing the model
svm = SVC(gamma='auto')
svm.fit(X_train,y_train)
svm.score(X_test, y_test)

0.9777777777777777

##### Decision Tree

In [10]:
# Creating an object,training and testing the model
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
dt.score(X_test, y_test)

0.9111111111111111

##### Random Forest

In [11]:
# Creating an object,training and testing the model
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9111111111111111

#### K-Fold Cross Validation

In [12]:
# Function to get score
def get_score(model, X_train, X_test, y_train, y_test):
  model.fit(X_train, y_train)
  return model.score(X_test, y_test)

In [13]:
# importing Stratified KFold
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [16]:
# Perform training  and getting Scores

scores_logistic = []
scores_svm = []
scores_dt = []
scores_rf = []

for train_index, test_index in folds.split(iris.data, iris.target):
  X_train,X_test,y_train,y_test = iris.data[train_index], iris.data[test_index],\
                                  iris.target[train_index], iris.target[test_index]
  
  scores_logistic.append(get_score(LogisticRegression(solver='lbfgs', max_iter=1000), X_train, X_test, y_train, y_test))
  scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
  scores_dt.append(get_score(DecisionTreeClassifier(), X_train, X_test, y_train, y_test))
  scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))


In [17]:
scores_logistic

[0.98, 0.96, 0.98]

In [18]:
scores_svm

[0.98, 0.98, 0.96]

In [20]:
scores_dt

[0.98, 0.92, 0.96]

In [19]:
scores_rf

[0.98, 0.94, 0.96]

#### Cros Val Score

In [21]:
from sklearn.model_selection import cross_val_score

##### Logistic Regression performance using Cross validation score

In [24]:
cross_val_score(LogisticRegression(solver='lbfgs', max_iter=1000), iris.data, iris.target, cv=3)

array([0.98, 0.96, 0.98])

##### SVM model performance using Cross validation score

In [25]:
cross_val_score(SVC(), iris.data, iris.target, cv=3)

array([0.96, 0.98, 0.94])

##### Dicision Tree model performance using Cross validation score

In [26]:
cross_val_score(DecisionTreeClassifier(), iris.data, iris.target, cv=3)

array([0.98, 0.92, 0.98])

##### Random Forest model performance using Cross validation score

In [27]:
cross_val_score(RandomForestClassifier(), iris.data, iris.target, cv=3)

array([0.98, 0.94, 0.96])