<a href="https://colab.research.google.com/github/GauraoM/ML-Basics-Definitions/blob/main/Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#Create a 3x3 matrix with values ranging from 0 to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
#Use NumPy to generate a random number between 0 and 1
np.random.rand(1)

array([0.22540685])

In [4]:
#Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
np.random.randint(1,100,25)

array([48, 89, 99, 97, 27, 19, 87,  2, 66,  6, 98, 27, 34, 74, 67,  6, 12,
       14, 70, 52, 49, 83, 90,  5, 94])

In [8]:
#Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Numpy Indexing and Selection

In [5]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [6]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [7]:
mat[3:,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])